title: Site

columns:
  - width: 1/2
    sections:
      pages:
        type:     customPages
        headline: Documentations
        info:     "{{ page.childrenAndDrafts.count }} chapter(s)"
        create:   documentation
        empty:    No documentations yet
        image:
          query: page.coverImage.toFile
          cover: true
